<?php

namespace App\Concerns;

use App\Classification\CodeLockedException;
use Illuminate\Database\Eloquent\Model;

/**
 * Chain-code immutability for the classification chain levels (ADR-0001).
 *
 * `kode_asset` is generated by concatenating the chain codes plus a
 * per-tenant sequence (rules §1.3), so changing a referenced code silently
 * invalidates every asset code built from it. Each model declares the child
 * model classes whose existing records lock its `code`; the updating hook
 * refuses the edit while any of them holds rows — fail-closed, before any
 * HTTP surface exists. Unreferenced codes stay editable so typos remain
 * fixable without a data migration.
 */
trait LocksCodeWhenReferenced
{
    /**
     * Boot the trait: refuse code edits on referenced rows.
     */
    public static function bootLocksCodeWhenReferenced(): void
    {
        static::updating(function (self $model): void {
            if (! $model->isDirty('code')) {
                return;
            }

            if (! $model->hasReferencingRecords()) {
                return;
            }

            throw new CodeLockedException(sprintf(
                'Cannot change the code of %s [%s] — child records already reference it (ADR-0001).',
                $model::class,
                $model->getOriginal('code'),
            ));
        });
    }

    /**
     * Whether any child level or item references this record — the lock
     * condition of ADR-0001. The lookup goes through the child model's
     * scoped query, so the check only ever sees this tenant's children.
     */
    public function hasReferencingRecords(): bool
    {
        foreach ($this->referencingModels() as $modelClass) {
            if ($modelClass::query()->where($this->getForeignKey(), $this->getKey())->exists()) {
                return true;
            }
        }

        return false;
    }

    /**
     * The child model classes whose existing records lock this model's
     * `code`.
     *
     * @return list<class-string<Model>>
     */
    abstract protected function referencingModels(): array;
}
