<?php

namespace App\Models;

use Database\Factories\TenantFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Stancl\Tenancy\Database\Models\Tenant as StanclTenant;

/**
 * Central tenant record (stancl/tenancy single-database mode).
 *
 * The row itself is central data — it must never be filtered by the tenant
 * scope, hence it does not use App\Concerns\BelongsToTenant. The string ULID
 * primary key is generated by the package's id generator binding; the
 * package's `tenants` conventions (data column, internal keys, run()) are
 * inherited unchanged.
 *
 * @property string $id
 * @property string $code
 * @property string $name
 * @property string $status
 */
class Tenant extends StanclTenant
{
    /** @use HasFactory<TenantFactory> */
    use HasFactory;

    /**
     * The attributes that are not mass assignable.
     *
     * The identifier is generated by the package's UniqueIdentifierGenerator
     * (fail-closed architecture decision) and must never come from request
     * input; everything else is admin/provisioning controlled.
     *
     * @var list<string>
     */
    protected $guarded = ['id'];

    /**
     * The real columns on the `tenants` table.
     *
     * The package's VirtualColumn trait serializes every attribute NOT
     * listed here into the `data` JSON column; declaring our columns keeps
     * them queryable with plain SQL (and indexable — `code` is unique).
     *
     * @return list<string>
     */
    public static function getCustomColumns(): array
    {
        return ['id', 'code', 'name', 'status'];
    }
}
